# This is a basic workflow to help you get started with Actions

# Name of the workflow
name: deploy

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for 
  # the main branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run 
# sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ['3.10', '3.11', '3.12', '3.13']

    # Steps represent a sequence of tasks that will be executed as 
    # part of the job
    steps:
      # Checks-out your repository so your job can access it
      - name: Check-out repository
        uses: actions/checkout@v2

      # Set up Python
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .[tests, dev]

      # Run pytest with coverage
      - name: Run tests with coverage
        run: |
          pytest --cov --cov-report=term --cov-branch

      - name: hatch build
        run: |
          hatch build

      - name: Publish to TestPyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        # if: steps.release.outputs.released == 'true'
        with:
          repository-url: https://test.pypi.org/legacy/
          password: ${{ secrets.TEST_PYPI_API_TOKEN }}

      - name: Test install from TestPyPI
        # if: steps.release.outputs.released == 'true'
        run: |
            pip install \
            --index-url https://test.pypi.org/simple/ \
            --extra-index-url https://pypi.org/simple \
            root_finding